### ISSUE TITLE
Add basic appdata quality checks

### ISSUE THREAD

**Issue by bertob** [flathub-infra/flatpak-builder-lint#156]
We have new [appdata quality guidelines](https://docs.flathub.org/docs/for-app-authors/appdata-guidelines/quality-guidelines) now, some of which could be relatively easily checked in an automated way, including:

- [ ] Icon fills the entire canvas (no transparent pixels)
- [ ] Icon is a symbolic (i.e. all non-transparent pixels are the same color)
- [x] Summary ending with dot (".")
- [x] Name >20 characters
- [x] Summary >35 characters
- [x] No screenshot captions
- [x] Developer field is not empty

**Comment by hfiguiere** [comment]
That require writing a brand new tool that will be run on the content of the flatpak AFTER the build.

**Comment by razzeee** [comment]
@bertob we should probably mention, that we only want to look at the english strings for now. (I have been thinking about translation in the past days)

**Comment by bbhtt** [comment]
3, 4 and 5 are in https://github.com/flathub-infra/flatpak-builder-lint/pull/246. Neither appstream-util or appstreamcli warns on 3 and 4. appstreamcli warns for 5 only in pedantic mode.

**Comment by bbhtt** [comment]
The icon checks are in the website moderation board nowadays. I don't think adding them in the linter makes sense, because at most we can raise a warning which is not very useful.

The moderation dashboard can provide a UI for the canvas etc.
