### ISSUE TITLE
Investigate if `org.freedesktop.portal.*` permissions are needed

### ISSUE THREAD

**Issue by bbhtt** [flathub-infra/flatpak-builder-lint#178]
Afaiu, these are allowed by flatpak itself https://github.com/flatpak/flatpak/blob/f66b1ecb7420ba56bc57cada92a1ed01a5a330f9/common/flatpak-run-dbus.c#L290-L294 and there should be no reason to put a `--talk-name` to them in app manifest since that allows for wider access than what flatpak gives by default.

Around ~36 apps are using it based on a Github search

The most common one being `org.freedesktop.portal.Fcitx` which seems to have [originated](https://github.com/flatpak/flatpak/issues/2031#issuecomment-482567827) from a fcitx bug back in 2018 https://github.com/flatpak/flatpak/issues/2031 and since been [fixed](https://github.com/fcitx/fcitx/commit/1f4c3a96cb2d1308581864676dd86ea6aa393ccb) on fcitx 4.2.9.7 (even Debian oldstable has newer fcitx than that https://packages.debian.org/search?keywords=fcitx&searchon=names&suite=all&section=all)

Another one popular one seems to be the background portal which seems to be not required at all to keep the app alive eg. https://github.com/flathub/org.signal.Signal/pull/524

I think these should be error-ed by default in the linter

**Comment by bbhtt** [comment]
Hi @smcv, can you please comment here, if this is correct?

**Comment by ebassi** [comment]
Correct: interfaces under `org.freedesktop.portal.` are automatically added to the allowlist, otherwise portals would never work out of the box.

**Comment by bbhtt** [comment]
Thanks!

Just for completeness, I asked in #xdg-desktop-portals:matrix.org to confirm my understanding in OP before I went on to break a bunch of app builds.
