### ISSUE TITLE
Check for icon sizes

### ISSUE THREAD

**Issue by hadess** [flathub-infra/flatpak-builder-lint#244]
I've just [built BambuStudio](https://github.com/flathub/flathub/pull/4822) and didn't have smaller size icons installed, just 256x256 and 512x512.

This resulted in a broken icon in gnome-shell.
![image](https://github.com/flathub-infra/flatpak-builder-lint/assets/769861/7880b10a-329a-4b74-9349-e74b0bf76504)

The linter should probably check, after the build, that the software installs a wider array of icon sizes.

**Comment by bbhtt** [comment]
Your 128px icon is named wrong, it wasn't exported at all 

![image](https://github.com/flathub-infra/flatpak-builder-lint/assets/62639087/f92ed11e-d67e-42cc-a353-6a5a78eb3158)

The icon name in the exported desktop file is wrong. It can't load an icon flatpak didn't export

![image](https://github.com/flathub-infra/flatpak-builder-lint/assets/62639087/0245477f-7c98-4b6d-b74c-caf40e9ef5ca)

**Comment by bbhtt** [comment]
> The linter should probably check, after the build, that the software installs a wider array of icon sizes.

This depends on application to application. Some might require a 16px png icon specifically for tray, if it is a svg there is nothing to check, for most 512px is enough because appstream creates 64px and 128px pngs from it

**Comment by hadess** [comment]
There were certainly a whole bunch of errors in that code. My excuse is that the build takes ages... Seems that we agree that there's room for improvement on the linter side though, right?

**Comment by bbhtt** [comment]
Yea, it should definitely check desktop files, which would've caught this. I thought appstream would've failed here, given how picky it is.

**Comment by hfiguiere** [comment]
if it export a 256x256 or 512x512, appstream compose will generate what is need things will work.

we do check icon size on buildbot. Even before the linter.

**Comment by bbhtt** [comment]
https://github.com/flathub-infra/flatpak-builder-lint/pull/245 will catch the main issue here.

> The icon name in the exported desktop file is wrong.
