### ISSUE TITLE
Linter output unusable direclty in a JSON parser since e35882e

### ISSUE THREAD

**Issue by tytan652** [flathub-infra/flatpak-builder-lint#285]
The linter is expected since many versions to output a JSON output, e35882ea16d74d95ef5d5a8b891960b5e6938133 broke this behavior. So it can no longer be used directly in a JSON parser such as jq.

**Comment by bbhtt** [comment]
What are you using it in jq for?

**Comment by tytan652** [comment]
Parse the JSON in a custom Github Action with a error filter for errors that should be ignored outside of release (e.g. screenshot) to wrote them as annotations readable in the run summary.

- Run summary with modified 2.1.5: https://github.com/obsproject/obs-studio/actions/runs/7864101487?pr=10234
- Action YAML: https://github.com/obsproject/obs-studio/blob/ae1ab38de3fc8d06e3b059b96860800afc05222a/.github/actions/flatpak-builder-lint/action.yaml
