### ISSUE TITLE
buildbot: Wrong file names

### ISSUE THREAD

**Issue by yakushabb** [flathub-infra/flatpak-builder-lint#386]
The following error captured from build-bot (https://buildbot.flathub.org/#/builders/6/builds/118075)

The filename on the output is wrong.

![resim](https://github.com/flathub-infra/flatpak-builder-lint/assets/161761531/21ac097b-97ba-4754-a225-1c2923ac9ff2)

**Comment by hfiguiere** [comment]
I don't see what's wrong

**Comment by yakushabb** [comment]
The desktop file does not contain a screenshot or desktop app information. These details are from the metadata file. However, the error suggests that they belong to the desktop file. In reality, the desktop file is only 10 lines long.

- https://gitlab.gnome.org/GNOME/office-runner/-/blob/master/src/org.gnome.OfficeRunner.desktop.in?ref_type=heads
- https://gitlab.gnome.org/GNOME/office-runner/-/blob/master/src/org.gnome.OfficeRunner.appdata.xml.in?ref_type=heads

**Comment by hfiguiere** [comment]
that's not the file name, that's the app-id how it is specified in the appstream file? 

Confused? appstreamcli is as well.

But nothing wrong from our side.

**Comment by yakushabb** [comment]
Thanks, I assumed the desktop as a file.
