### ISSUE TITLE
Auto-merging org.qownnotes.QOwnNotes

### ISSUE THREAD

**Issue by pbek** [flathub-infra/flatpak-builder-lint#428]
Is there a way to get an exemption for [org.qownnotes.QOwnNotes](https://github.com/flathub/org.qownnotes.QOwnNotes/) to be auto-merged?
All releases are tested upstream and there are no other dependencies which can break something when updated. 🙏🏻

**Comment by Erick555** [comment]
> "No other dependencies" does not seem correct, the main binary is using 41 libraries from runtime. The runtime has its own API/ABI different from distributions

I meant no dependencies shipped in app (except git used as cli tool). Runtime API/ABI is supposed to be stable otherwise it's bug.

In general auto-merged update is as tested as manual update except developer must go to flathub and click the button all the time. There is no benefit for flathub.

**Comment by bbhtt** [comment]
We decided to allow newly verified applications access to automerge, I have added the exception in https://github.com/flathub-infra/flatpak-builder-lint/pull/458

**Comment by pbek** [comment]
Hey, thank you very much!

**Comment by Erick555** [comment]
@pbek you need to revert https://github.com/flathub/org.qownnotes.QOwnNotes/commit/ac553fe7d54e40429633a9cc1c232a2d4ea4ada8 to re-enable auto-merging

**Comment by pbek** [comment]
I thought as much. 😉 Doing #284 now...
