### ISSUE TITLE
Repo lint following official docs does not work

### ISSUE THREAD

**Issue by vemonet** [flathub-infra/flatpak-builder-lint#509]
Following description available at https://docs.flathub.org/docs/for-app-authors/linter/

I run the linter inside when at the root of my repo cloned locally: https://github.com/flathub/io.github.vemonet.EmojiMart 

In the first command it is obvious we need to provide the manifest path because the docs uses brackets `<manifest>`

But for the repo lint it says `repo repo`... Which is quite enigmatic (should not be)

And of course the docs with "more details" is not giving any more clarifications: https://github.com/flathub-infra/flatpak-builder-lint/blob/master/README.md

I tried to just run this:
```bash
flatpak run --command=flatpak-builder-lint org.flatpak.Builder repo repo
```

Getting an error

The `flatpak run --command=flatpak-builder-lint org.flatpak.Builder --help` says it should be a path so I try with a path:

```
usage: flatpak-builder-lint [-h] [--version] [--exceptions] [--appid APPID]
                            [--cwd] [--ref REF]
                            {builddir,repo,manifest,appstream} path

A linter for Flatpak builds and flatpak-builder manifests

positional arguments:
  {builddir,repo,manifest,appstream}
                        type of artifact to lint
  path                  path to artifact
```

So running giving a path:

```bash
flatpak run --command=flatpak-builder-lint org.flatpak.Builder repo .
```

Same error, no directory:

```
Traceback (most recent call last):
  File "/app/bin/flatpak-builder-lint", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/app/lib/python3.11/site-packages/flatpak_builder_lint/cli.py", line 179, in main
    if results := run_checks(args.type, path, args.exceptions, args.appid):
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/flatpak_builder_lint/cli.py", line 76, in run_checks
    check_method(check_method_arg)
  File "/app/lib/python3.11/site-packages/flatpak_builder_lint/checks/appid.py", line 112, in check_repo
    self._populate_ref(path)
  File "/app/lib/python3.11/site-packages/flatpak_builder_lint/checks/__init__.py", line 26, in _populate_ref
    self.repo_primary_ref = ostree.get_primary_ref(repo)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/flatpak_builder_lint/ostree.py", line 27, in get_primary_ref
    refs = get_refs(repo_path, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/flatpak_builder_lint/ostree.py", line 20, in get_refs
    repo = open_ostree_repo(repo_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/flatpak_builder_lint/ostree.py", line 13, in open_ostree_repo
    if not repo.open(None):
           ^^^^^^^^^^^^^^^
gi.repository.GLib.GError: g-io-error-quark: opening repo: opendir(objects): No such file or directory (1)
```

How should it be run to lint the repo locally?

Could you fix the docs please? And the  `--help` output because the lint repo clearly does not take a path to a repo.

@bbhtt

**Comment by bbhtt** [comment]
The docs are fine, you have to build and export it to a repo first called `repo`.

**Comment by bbhtt** [comment]
It's not a GitHub repo, use flatpak-builder with `--repo=repo`.

**Comment by vemonet** [comment]
The docs are unclear at the very least 

"It's not a GitHub repo," ok but what is it?

What is a repo? A local folder?

**Comment by vemonet** [comment]
It looks like a joke honestly haha

I have a `build` folder that is generated when running flatpak build, that's it @bbhtt

**Comment by bbhtt** [comment]
> use flatpak-builder with --repo=repo

When building it with flatpak builder export it to a repo using that. It's that.

**Comment by vemonet** [comment]
Ah ok the `repo` used in `flatpak run org.flatpak.Builder --keep-build-dirs --user --install --force-clean build io.github.vemonet.EmojiMart.yml --repo=.repo`

Repo is a bit confusing here it's more a `--dir` or `--folder`

**Comment by bbhtt** [comment]
Added some more info to readme https://github.com/flathub-infra/flatpak-builder-lint?tab=readme-ov-file#checks and to https://docs.flathub.org/docs/for-app-authors/linter/

**Comment by vemonet** [comment]
Thanks that's clearer, in my case the problem was that I slightly changed the `repo` to `.repo` in the scripts to make it a hidden folder, and forgot about this folder (we usually only deal with the `build` folder when debugging)
